version: '3.9'
services:

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - /home/colbits/Desktop/Luis/Docker_Compose/Mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always
#    networks:
#      - TestNet
    
  mynodered:
    image: nodered/node-red
    ports:
      - 1880:1880
    volumes:
      - node_red_data:/data  
    links:
      - mosquitto
#    networks:
#      - TestNet

volumes:
  node_red_data:
  conf:
networks:  
  external: true
#  TestNet:
#    driver: bridge
#   driver_opts:
#     com.docker.network.enable_ipv6: "true"